language: ruby
branches:
  only:
    - gh-pages
    - /.*/
rvm:
- 2.6.1
before_install:
- gem update --system
install:
- gem install bundler
after_install:
- bundler update --bundler
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: gh-pages
