language: ruby
branches:
  only:
    - gh-pages
    - /.*/
rvm:
- 2.3.1
before_install:
- gem update --system
- bundle update
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: gh-pages
