# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               plou's tHoTFuL SPot
tagline:             'hi :)'
description:         'thoughts, endeavors, and ramblings'
url:                 'paullou.me/blog/'
baseurl:             ''

# About/contact
author:
  name:              Paul S. Lou
  url:               paullou.me
