plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  per_page: 1
  limit: 0
  title: ':title'
  sort_reverse: true

# Setup
theme: minimal-mistakes-jekyll
title:               plou's tHoTFuL SPot
tagline:             'hi :)'
description:         'thoughts, endeavors, and ramblings'
url:                 'paullou.me'
baseurl:             '/blog'

# About/contact
author:
  name:              Paul S. Lou
  url:               paullou.me
