# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               plous tHoTFuL SPot
tagline:             'hi :)'
description:         'thoughts, endeavors, and ramblings'
url:                 'paullou.me'
baseurl:             '/blog'

# About/contact
author:
  name:              Paul S. Lou
  url:               paullou.me

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

